name = "aiken-lang/hello_world"
description = "Aiken contracts for project 'aiken-lang/hello_world'"
version = "0.0.0"
license  = "Apache-2.0"
 
[repository]
user = 'aiken-lang'
project = 'hello_world'
platform = 'github'
 
[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"